"""
Reinforcement Learning Loop & Policy Optimizer for Sentix.
Processes experience replay logs (`data/rl_feedback.jsonl`) generated by the Go Gateway,
evaluates policy rewards, computes regret, and performs active dataset augmentation.
"""

import json
import os
import argparse
from typing import List, Dict, Any
from collections import defaultdict


DEFAULT_LOG_PATH = "data/rl_feedback.jsonl"
DEFAULT_OUTPUT_SUMMARY = "data/rl_summary.json"


def load_experiences(log_path: str = DEFAULT_LOG_PATH) -> List[Dict[str, Any]]:
    """Loads experience replay records from JSONL log."""
    if not os.path.exists(log_path):
        print(f"Warning: Replay log not found at {log_path}. Creating sample log...")
        os.makedirs(os.path.dirname(log_path) or ".", exist_ok=True)
        sample = {
            "timestamp": "2026-10-07T00:00:00Z",
            "request_id": "req-init-1",
            "text": "The display is crisp and vivid, but customer service was slow.",
            "engine_used": "onnx_distilbert_int8",
            "predicted_label": "NEGATIVE",
            "correct_label": "NEGATIVE",
            "reward": 1.0,
            "latency_ms": 9.3,
            "comment": "Accurate prediction on mixed review"
        }
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(json.dumps(sample) + "\n")

    records = []
    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return records


def analyze_rl_performance(records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Analyzes rewards, latencies, accuracy, and tier policy distribution."""
    if not records:
        return {"total_records": 0, "status": "no_data"}

    total = len(records)
    tier_stats = defaultdict(lambda: {"count": 0, "rewards": [], "latencies": [], "correct": 0, "labeled": 0})
    misclassified = []

    for r in records:
        engine = r.get("engine_used", "unknown")
        reward = float(r.get("reward", 0.0))
        latency = float(r.get("latency_ms", 0.0))
        pred = r.get("predicted_label", "").lower()
        actual = r.get("correct_label", "").lower()

        tier_stats[engine]["count"] += 1
        tier_stats[engine]["rewards"].append(reward)
        if latency > 0:
            tier_stats[engine]["latencies"].append(latency)

        if actual:
            tier_stats[engine]["labeled"] += 1
            if pred == actual:
                tier_stats[engine]["correct"] += 1
            else:
                misclassified.append({
                    "text": r.get("text", ""),
                    "predicted": pred,
                    "actual": actual,
                    "engine": engine,
                    "reward": reward
                })

    summary_per_tier = {}
    for engine, s in tier_stats.items():
        avg_reward = sum(s["rewards"]) / len(s["rewards"]) if s["rewards"] else 0.0
        avg_latency = sum(s["latencies"]) / len(s["latencies"]) if s["latencies"] else 0.0
        labeled_count = s["labeled"]
        accuracy = (s["correct"] / labeled_count * 100) if labeled_count > 0 else None

        summary_per_tier[engine] = {
            "selections": s["count"],
            "share_pct": round((s["count"] / total) * 100, 2),
            "average_reward": round(avg_reward, 4),
            "avg_latency_ms": round(avg_latency, 2),
            "accuracy_pct": round(accuracy, 2) if accuracy is not None else "N/A"
        }

    overall_avg_reward = sum(float(r.get("reward", 0.0)) for r in records) / total

    return {
        "total_experiences": total,
        "overall_average_reward": round(overall_avg_reward, 4),
        "tiers": summary_per_tier,
        "misclassified_samples_count": len(misclassified),
        "active_learning_candidates": misclassified[:10]
    }


def run_rl_pipeline(
    log_path: str = DEFAULT_LOG_PATH,
    output_path: str = DEFAULT_OUTPUT_SUMMARY,
    retrain_threshold: int = 50
) -> Dict[str, Any]:
    """Runs full RL loop analysis and saves summary."""
    print("=" * 65)
    print("Sentix Reinforcement Learning: Policy Optimizer & Buffer Analysis")
    print("=" * 65)

    records = load_experiences(log_path)
    print(f"Loaded {len(records)} experience feedback records from {log_path}.")

    analysis = analyze_rl_performance(records)
    print(f"\nOverall Average Reward: {analysis['overall_average_reward']}")
    print("\nTier Policy Breakdown:")
    for tier, stats in analysis["tiers"].items():
        print(f"  • {tier}: {stats['selections']} calls ({stats['share_pct']}%) | Avg Reward: {stats['average_reward']} | Latency: {stats['avg_latency_ms']}ms")

    if analysis["misclassified_samples_count"] > 0:
        print(f"\nIdentified {analysis['misclassified_samples_count']} candidate samples for active learning re-training.")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2)
    print(f"\nSaved RL policy summary report to: {output_path}")

    return analysis


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sentix Reinforcement Learning Loop Optimizer")
    parser.add_argument("--log-path", type=str, default=DEFAULT_LOG_PATH, help="Path to rl_feedback.jsonl")
    parser.add_argument("--output", type=str, default=DEFAULT_OUTPUT_SUMMARY, help="Output summary JSON path")
    args = parser.parse_args()

    run_rl_pipeline(log_path=args.log_path, output_path=args.output)
